### ISSUE TITLE
NMR Challenge

### ISSUE THREAD

**Issue by BoGGoG** [ML4SCI/DeepLearnHackathon#13]
- in the first cell, where the data is downloaded, there is a line `asdf = "..."` that I think is not used.
- Last paragraph in notebook: "resulst" -> "results"
- Performance visualization: It's alpha_x, alpha_z and theta, right? Why are they here called alpha, xi and d? I also don't understand the figure titles.

**Comment by ereinha** [comment]
* Reincluded the asdf = "..." to shorten file links
* Fixed typo
* Older 2021 problem description was used which didn't match current hackathon. Updated to more recent problem description
