### ISSUE TITLE
Exoplanet Search Challenge

### ISSUE THREAD

**Issue by BoGGoG** [ML4SCI/DeepLearnHackathon#18]
Cool challenge!

- [x] Is there a way to download the sample data in the notebook? Maybe similar to the first two cells [in this notebook](https://github.com/ML4SCI/DeepLearnHackathon/blob/main/HiggsBosonClassificationChallenge/higgs_classification.ipynb) or with `requests` [here](https://github.com/ML4SCI/DeepLearnHackathon/blob/main/NMRSpinChallenge/Hackathon_NMR_Challenge_July2024.ipynb)? Might have to zip the `Sample_Data` folder on the Google Drive. For the full dataset I think it's okay if we tell them to download it from a link, but it would be cool if the example notebook simply works if one goes through the cells.
- [x] The other challenges have the notebook also in the repo and not just as a Colab link. Can you also upload it in the repo?

edit:
- [x] Also, the `train_info.csv` from the download is called `planet_info.csv` in the notebook, right? Is this the same file?
- [x] Might be a good idea to also zip the full dataset, since otherwise Google zips it every time one wants to download it.

Cheers!

**Comment by j-p-terry** [comment]
The first three are solved. I'll do the fourth ASAP, but I have terrible internet right now and can't upload that much data

**Comment by BoGGoG** [comment]
Collecting stuff that Sergei mentioned here:
- [ ] Instructions from Readme at top of notebook
- [ ] more text and explanations
- [ ] data download: using google drive in notebook
